// Curated topic pool. Each entry is a real Wikipedia article title plus a
// one-line "why it's worth knowing". Picked for usefulness and "huh, I never
// knew that" value rather than breadth: things that change how you think,
// spend, eat, stay healthy, or understand the world around you.
// Loaded by index.html in the browser and by server.js (for default categories).
const TOPIC_POOL = [
  {
    name: 'Money',
    color: '#d9a441',
    topics: [
      ['Compound interest', 'Why small savings started early beat big savings started late.'],
      ['Index fund', 'The boring investment that quietly outperforms most professionals.'],
      ['Inflation', 'Why cash sitting still is slowly losing value every year.'],
      ['Opportunity cost', 'The real price of anything is what you gave up to get it.'],
      ['Diversification (finance)', 'The math behind not putting all your eggs in one basket.'],
      ['Rule of 72', 'Mental math for how fast money (or debt) doubles.'],
      ['Dollar-cost averaging', 'A way to invest steadily without trying to time the market.'],
      ['Time value of money', 'Why a dollar today is worth more than a dollar next year.'],
      ['Efficient-market hypothesis', 'Why consistently beating the market is so hard.'],
      ['Supply and demand', 'The model behind nearly every price you pay.'],
      ['Comparative advantage', 'Why trade makes both sides richer, even if one is better at everything.'],
      ['Moral hazard', 'How insurance and safety nets change how people behave.'],
      ['Tragedy of the commons', 'Why shared resources get overused, and the ways communities avoid it.'],
      ['Fractional-reserve banking', 'Where most of the money in the economy actually comes from.'],
      ['Economic bubble', 'Tulips, dot-coms, housing: how financial manias form and pop.'],
      ['Hyperinflation', 'What happens when a currency stops holding value.'],
      ['Price discrimination', 'Why two people can pay different prices for the same thing.'],
      ['Loss leader', 'Why stores happily sell some items at a loss.'],
      ['Credit score in the United States', 'How lenders score you, and what actually moves the number.'],
      ['Individual retirement account', 'How the tax code rewards saving for later.'],
      ['Emergency fund', 'The unglamorous buffer that keeps small shocks from becoming debt.'],
      ['Stock', 'What owning a share of a company actually means.'],
      ['Bond (finance)', 'How lending money to governments and companies works.']
    ]
  },
  {
    name: 'Mind',
    color: '#c77dba',
    topics: [
      ['Confirmation bias', 'Your brain seeks evidence for what you already believe.'],
      ['Dunning–Kruger effect', 'Why beginners overrate themselves and experts underrate themselves.'],
      ['Sunk cost', 'Why "I\'ve already invested so much" is a trap.'],
      ['Loss aversion', 'Losing $100 hurts more than winning $100 feels good.'],
      ['Anchoring effect', 'The first number you hear skews every judgment after it.'],
      ['Hedonic treadmill', 'Why new purchases and promotions stop feeling special so fast.'],
      ['Flow (psychology)', 'The state of deep focus, and the conditions that trigger it.'],
      ['Cognitive dissonance', 'How people twist beliefs to match what they already did.'],
      ['Placebo', 'Expectation alone can produce real, measurable effects.'],
      ['Bystander effect', 'Why a crowd is less likely to help than one person.'],
      ['Availability heuristic', 'Why vivid events feel more common than they are.'],
      ['Spacing effect', 'The single most reliable way to remember what you learn.'],
      ['Testing effect', 'Recalling information cements it better than rereading it.'],
      ['Fundamental attribution error', 'We blame others\' character but excuse ourselves by circumstance.'],
      ['Planning fallacy', 'Why every project takes longer than you think.'],
      ['Survivorship bias', 'Learning only from winners hides why most people lose.'],
      ['Social proof', 'We copy what others do, especially when unsure.'],
      ['Framing effect (psychology)', 'The same fact phrased two ways leads to different choices.'],
      ['Procrastination', 'Why we delay things we want done, and what actually helps.'],
      ['Habit', 'How routines form in the brain and how to rebuild them.'],
      ['Impostor syndrome', 'Why capable people feel like frauds.'],
      ['Stanford marshmallow experiment', 'The famous willpower study and what later research changed.'],
      ['Reciprocity (social psychology)', 'The powerful urge to return favors, and how it gets exploited.']
    ]
  },
  {
    name: 'Health',
    color: '#5fb88a',
    topics: [
      ['Sleep', 'What your brain and body are doing during the third of life you spend asleep.'],
      ['Circadian rhythm', 'Your internal clock, and why light timing matters so much.'],
      ['Gut microbiota', 'The trillions of microbes in your gut that influence far more than digestion.'],
      ['VO2 max', 'One of the strongest predictors of long-term health, and it\'s trainable.'],
      ['Insulin resistance', 'The quiet precursor to type 2 diabetes and how lifestyle reverses it.'],
      ['Dietary fiber', 'The nutrient most people don\'t get enough of.'],
      ['Muscle hypertrophy', 'How muscles actually grow, and what drives it.'],
      ['Cortisol', 'The stress hormone: useful in bursts, harmful when chronic.'],
      ['Dopamine', 'Not the "pleasure chemical"; it\'s about wanting and motivation.'],
      ['Neuroplasticity', 'Your brain physically rewires itself with practice at any age.'],
      ['Caffeine', 'How it blocks tiredness signals, and why timing matters for sleep.'],
      ['Immune system', 'How your body tells friend from foe.'],
      ['Vaccine', 'How training the immune system in advance works.'],
      ['Antimicrobial resistance', 'Why antibiotics are losing effectiveness worldwide.'],
      ['Heart rate variability', 'A window into stress, recovery, and fitness.'],
      ['Protein (nutrient)', 'How much you need and what your body does with it.'],
      ['Blood sugar level', 'Why spikes and crashes affect energy and mood.'],
      ['Long-term effects of alcohol', 'What regular drinking does to the body over years.'],
      ['Cardiopulmonary resuscitation', 'A skill that doubles someone\'s odds of surviving cardiac arrest.'],
      ['Sunscreen', 'How SPF works and why it\'s the best anti-aging tool there is.'],
      ['Mediterranean diet', 'One of the most studied eating patterns for longevity.'],
      ['Meditation', 'What the research says it does (and doesn\'t) do.'],
      ['Tooth decay', 'How cavities form and why sugar frequency matters more than amount.']
    ]
  },
  {
    name: 'How Things Work',
    color: '#5aa7d6',
    topics: [
      ['Internal combustion engine', 'The four-stroke cycle that moved the 20th century.'],
      ['Electric motor', 'How magnetism turns electricity into motion.'],
      ['Lithium-ion battery', 'What\'s inside the battery in your phone, laptop, and car.'],
      ['Transistor', 'The tiny switch behind every piece of modern electronics.'],
      ['Heat pump', 'How moving heat (instead of making it) is 3–4× more efficient.'],
      ['Vapor-compression refrigeration', 'How your fridge pushes heat out of a box.'],
      ['Global Positioning System', 'How satellites and relativity pinpoint your location.'],
      ['Microwave oven', 'How it heats food from the water molecules outward.'],
      ['Solar cell', 'How sunlight knocks electrons loose to make power.'],
      ['Jet engine', 'Suck, squeeze, bang, blow: how planes are propelled.'],
      ['Lift (force)', 'Why wings actually generate lift (it\'s not the popular explanation).'],
      ['Electrical grid', 'The continent-sized machine that has to balance itself every second.'],
      ['Touchscreen', 'How your screen knows exactly where your finger is.'],
      ['Wi-Fi', 'How data rides radio waves through your walls.'],
      ['Containerization', 'The humble steel box that made global trade cheap.'],
      ['Concrete', 'The most used material on Earth after water.'],
      ['Suspension bridge', 'How cables carry massive loads across huge spans.'],
      ['Anti-lock braking system', 'Why pumping the brakes is now done for you.'],
      ['Nuclear power', 'How splitting atoms boils water to make electricity.'],
      ['Water purification', 'The journey from river to tap.'],
      ['Barcode', 'How a pattern of lines runs the world\'s supply chains.'],
      ['Elevator', 'The safety brake that made skyscrapers possible.'],
      ['Flush toilet', 'The siphon trick that changed public health.']
    ]
  },
  {
    name: 'Thinking Tools',
    color: '#e07b53',
    topics: [
      ['Bayes\' theorem', 'How to update your beliefs properly when new evidence arrives.'],
      ['Occam\'s razor', 'Prefer the explanation with the fewest assumptions.'],
      ['First principle', 'Reasoning from the ground up instead of by analogy.'],
      ['Game theory', 'The math of strategic decisions when others are deciding too.'],
      ['Prisoner\'s dilemma', 'Why two rational people might not cooperate, even when it helps both.'],
      ['Pareto principle', 'Roughly 80% of effects come from 20% of causes.'],
      ['Expected value', 'How to weigh uncertain outcomes when making decisions.'],
      ['Regression toward the mean', 'Why extreme results tend to be followed by ordinary ones.'],
      ['Correlation does not imply causation', 'The most common mistake in reading the news.'],
      ['Base rate fallacy', 'Why a "99% accurate" test can still be wrong most of the time.'],
      ['Goodhart\'s law', 'When a measure becomes a target, it stops being a good measure.'],
      ['Parkinson\'s Law', 'Work expands to fill the time available.'],
      ['Hanlon\'s razor', 'Don\'t assume malice when a mistake explains it.'],
      ['Law of large numbers', 'Why casinos always win in the long run.'],
      ['Exponential growth', 'Why humans consistently underestimate compounding.'],
      ['Unintended consequences', 'Well-meant actions often backfire in predictable ways.'],
      ['Perverse incentive', 'How rewards can make the problem worse.'],
      ['Black swan theory', 'Rare, unpredictable events that shape history the most.'],
      ['Map–territory relation', 'Your model of reality isn\'t reality.'],
      ['Straw man', 'Spotting and avoiding distorted versions of arguments.'],
      ['Socratic method', 'Questioning your way to clearer thinking.'],
      ['Falsifiability', 'What separates a scientific claim from an unfalsifiable one.'],
      ['Streisand effect', 'Why trying to hide something often spreads it.']
    ]
  },
  {
    name: 'History',
    color: '#b88a5f',
    topics: [
      ['Printing press', 'The invention that made knowledge cheap and upended Europe.'],
      ['Industrial Revolution', 'How machines and coal rewrote how humans live and work.'],
      ['Black Death', 'The pandemic that killed a third of Europe and reshaped its economy.'],
      ['Columbian exchange', 'Why tomatoes are Italian and potatoes fed Europe.'],
      ['Neolithic Revolution', 'The shift to farming that made cities and civilization possible.'],
      ['Scientific Revolution', 'When people started testing ideas instead of trusting authorities.'],
      ['Age of Enlightenment', 'Where modern ideas of rights, reason, and democracy come from.'],
      ['Silk Road', 'The trade network that moved goods, ideas, and plagues across Eurasia.'],
      ['Haber process', 'The chemistry that feeds roughly half the world\'s population.'],
      ['Green Revolution', 'How crop science averted mass famine in the 20th century.'],
      ['Great Depression', 'The economic collapse that shaped modern economic policy.'],
      ['Bretton Woods system', 'The deal that built the post-war global financial order.'],
      ['Marshall Plan', 'How rebuilding enemies turned into lasting alliances.'],
      ['Cold War', 'The 45-year standoff that shaped today\'s geopolitics.'],
      ['Cuban Missile Crisis', 'The 13 days the world came closest to nuclear war.'],
      ['Manhattan Project', 'The secret race to build the atomic bomb.'],
      ['Space Race', 'How rivalry put humans on the Moon in just 12 years.'],
      ['ARPANET', 'The military research network that became the internet.'],
      ['Spanish flu', 'The 1918 pandemic and its lessons for modern outbreaks.'],
      ['Fall of the Western Roman Empire', 'How a superpower slowly came apart.'],
      ['Magna Carta', 'The 1215 document that planted the idea that rulers are bound by law.'],
      ['Meiji Restoration', 'How Japan modernized at breathtaking speed.'],
      ['History of writing', 'How humans invented a way to store thoughts outside their heads.']
    ]
  },
  {
    name: 'Space & Physics',
    color: '#8a87e0',
    topics: [
      ['Big Bang', 'What we actually know about how the universe began.'],
      ['Black hole', 'Where gravity wins and even light can\'t escape.'],
      ['Speed of light', 'The universe\'s ultimate speed limit, and why it exists.'],
      ['Time dilation', 'Time literally runs at different speeds for different observers.'],
      ['General relativity', 'Gravity isn\'t a force; it\'s curved spacetime.'],
      ['Entropy', 'Why time has a direction and things fall apart.'],
      ['Quantum entanglement', 'The "spooky" link between particles, and what it really means.'],
      ['Double-slit experiment', 'The experiment that shows light and matter behave like waves.'],
      ['Dark matter', 'Most of the universe\'s matter is invisible.'],
      ['Exoplanet', 'How we find planets orbiting other stars, and how many there are.'],
      ['Fermi paradox', 'If aliens are likely, where is everybody?'],
      ['Tide', 'How the Moon (and Sun) move oceans twice a day.'],
      ['Season', 'It\'s the tilt, not the distance from the Sun.'],
      ['Aurora', 'How solar wind paints the polar skies.'],
      ['Nuclear fusion', 'The process powering the Sun, and the quest to bottle it.'],
      ['Neutron star', 'A teaspoon of it weighs as much as a mountain.'],
      ['Supernova', 'The explosions that made the atoms in your body.'],
      ['Gravitational wave', 'Ripples in spacetime we can now actually detect.'],
      ['Cosmic microwave background', 'The afterglow of the Big Bang, visible in every direction.'],
      ['Lagrange point', 'The gravitational parking spots where telescopes sit.'],
      ['James Webb Space Telescope', 'How we\'re seeing the first galaxies ever formed.'],
      ['Formation and evolution of the Solar System', 'How a cloud of gas became the Sun and planets.'],
      ['Standard Model', 'The rulebook for every known particle and force (except gravity).']
    ]
  },
  {
    name: 'Life & Nature',
    color: '#8fbf4a',
    topics: [
      ['Evolution', 'The single idea that makes sense of all of biology.'],
      ['Convergent evolution', 'Why unrelated animals keep evolving the same solutions.'],
      ['DNA', 'The molecule that stores the instructions for every living thing.'],
      ['CRISPR gene editing', 'Find-and-replace for DNA, and why it\'s so revolutionary.'],
      ['Photosynthesis', 'How plants turn sunlight into the energy nearly all life runs on.'],
      ['Mycorrhiza', 'The fungal networks that connect and feed forests.'],
      ['Tardigrade', 'The near-indestructible micro-animal that survives space.'],
      ['Octopus', 'A genuinely alien intelligence here on Earth.'],
      ['Bird migration', 'How birds navigate thousands of kilometres with pinpoint accuracy.'],
      ['Keystone species', 'Why removing one species can collapse an ecosystem.'],
      ['Symbiogenesis', 'Your cells contain ancient bacteria that moved in for good.'],
      ['Coral reef', 'Rainforests of the sea, and why they\'re bleaching.'],
      ['Pollination', 'The partnership a third of our food depends on.'],
      ['Cambrian explosion', 'When most major animal groups appeared in a geological blink.'],
      ['Cretaceous–Paleogene extinction event', 'The asteroid that ended the dinosaurs and opened the door for mammals.'],
      ['Virus', 'Not quite alive, yet shaping all of life.'],
      ['Bioluminescence', 'Why so much of the deep ocean glows.'],
      ['Honey bee', 'A superorganism with a language of dance.'],
      ['Epigenetics', 'How environment switches genes on and off.'],
      ['Human evolution', 'The story of how our species came to be.'],
      ['Whale fall', 'A single dead whale feeds a deep-sea ecosystem for decades.'],
      ['Mimicry', 'The evolutionary art of pretending to be something else.'],
      ['Animal cognition', 'What crows, apes, and dolphins reveal about intelligence.']
    ]
  },
  {
    name: 'Earth & Climate',
    color: '#3fb5b0',
    topics: [
      ['Plate tectonics', 'Why continents move, mountains rise, and earthquakes happen.'],
      ['Greenhouse effect', 'The physics that keeps Earth warm, and why more CO₂ warms it further.'],
      ['Water cycle', 'The loop that moves every drop of water on the planet.'],
      ['Thermohaline circulation', 'The ocean\'s global conveyor belt of heat.'],
      ['El Niño–Southern Oscillation', 'The Pacific pattern that shifts weather worldwide.'],
      ['Jet stream', 'The high-altitude river of wind that steers weather.'],
      ['Carbon cycle', 'How carbon moves between air, oceans, rock, and life.'],
      ['Earthquake', 'What\'s happening underground when the ground shakes.'],
      ['Volcano', 'How molten rock reaches the surface and reshapes the planet.'],
      ['Tropical cyclone', 'How hurricanes form and why they\'re intensifying.'],
      ['Ozone depletion', 'An environmental crisis humanity actually solved.'],
      ['Ice age', 'Earth has swung between frozen and warm many times.'],
      ['Milankovitch cycles', 'The orbital wobbles that pace the ice ages.'],
      ['Soil', 'The living skin of the planet that grows our food.'],
      ['Aquifer', 'The hidden groundwater much of the world drinks.'],
      ['Weather forecasting', 'How supercomputers predict tomorrow, and why it gets fuzzy past a week.'],
      ['Lightning', 'How storms build up billions of volts.'],
      ['Wildfire', 'Why fire is both destructive and essential to many ecosystems.'],
      ['Sea level rise', 'How much, how fast, and what drives it.'],
      ['Permafrost', 'The frozen ground holding huge amounts of carbon.'],
      ['Tsunami', 'How a seafloor jolt becomes a wall of water.'],
      ['Desalination', 'Turning seawater into drinking water, and its cost.'],
      ['Renewable energy', 'How wind, solar, and hydro are reshaping the grid.']
    ]
  },
  {
    name: 'Philosophy',
    color: '#d6727a',
    topics: [
      ['Stoicism', 'Focus on what you can control; a 2,000-year-old toolkit for resilience.'],
      ['Epicureanism', 'The real philosophy of pleasure: simple, calm, and with friends.'],
      ['Utilitarianism', 'Judging actions by how much good they produce.'],
      ['Categorical imperative', 'Act only in ways you\'d want everyone to act.'],
      ['Existentialism', 'Meaning isn\'t given to you; you create it.'],
      ['Absurdism', 'Camus on living fully in a universe that doesn\'t explain itself.'],
      ['Social contract', 'Why we accept governments at all.'],
      ['Original position', 'Design a fair society without knowing who you\'d be in it.'],
      ['Trolley problem', 'The thought experiment behind self-driving car ethics.'],
      ['Ship of Theseus', 'If you replace every part, is it still the same thing? (Are you?)'],
      ['Allegory of the cave', 'Plato on mistaking shadows for reality.'],
      ['Cogito, ergo sum', 'The one thing Descartes decided he couldn\'t doubt.'],
      ['Problem of induction', 'Why the sun rising every day doesn\'t prove it will tomorrow.'],
      ['Is–ought problem', 'You can\'t get what should be from what is alone.'],
      ['Free will', 'Are your choices really yours?'],
      ['Four Noble Truths', 'The Buddha\'s core diagnosis of suffering and its cure.'],
      ['Golden mean (philosophy)', 'Aristotle: virtue is the middle between two extremes.'],
      ['Memento mori', 'Remembering death as a tool for living well.'],
      ['Wabi-sabi', 'The Japanese aesthetic of finding beauty in imperfection.'],
      ['Ikigai', 'The Japanese idea of a reason for being.'],
      ['Separation of powers', 'Why good governments split power against itself.'],
      ['Rule of law', 'The idea that no one is above the rules.'],
      ['Epistemology', 'How do you know what you know?']
    ]
  },
  {
    name: 'Food Science',
    color: '#e0a05a',
    topics: [
      ['Maillard reaction', 'The browning reaction behind nearly everything that tastes "cooked".'],
      ['Caramelization', 'What happens to sugar under heat, step by step.'],
      ['Fermentation in food processing', 'Microbes turning food into bread, beer, cheese, and kimchi.'],
      ['Sourdough', 'The wild yeast and bacteria partnership behind naturally leavened bread.'],
      ['Emulsion', 'How mayonnaise and vinaigrettes hold oil and water together.'],
      ['Umami', 'The fifth taste, and how to add it to anything.'],
      ['Gluten', 'The protein network that gives bread its chew.'],
      ['Smoke point', 'Why choosing the right oil for the heat matters.'],
      ['Brining', 'How salt water makes meat juicier.'],
      ['Sous vide', 'Precise-temperature cooking and the science of doneness.'],
      ['Capsaicin', 'Why chili burns, and why milk (not water) helps.'],
      ['Food preservation', 'Salting, drying, canning, freezing: how food stays safe.'],
      ['Pasteurization', 'The gentle heating that made milk safe to drink.'],
      ['Foodborne illness', 'What actually causes food poisoning and how to avoid it.'],
      ['Cast-iron cookware', 'Why seasoning works and how to care for it.'],
      ['Coffee roasting', 'How green beans become the flavors in your cup.'],
      ['Taste', 'How your tongue and nose work together to create flavor.'],
      ['Yeast', 'The single-celled fungus behind bread, beer, and wine.'],
      ['Olive oil', 'What "extra virgin" means and why it matters.'],
      ['Chocolate', 'From bitter bean to bar: fermentation, roasting, and tempering.'],
      ['Tea', 'One plant, and how processing makes it green, black, or oolong.'],
      ['Salt', 'The mineral that shaped trade, empires, and every recipe.'],
      ['Knife sharpening', 'How an edge actually cuts, and how to keep it sharp.']
    ]
  },
  {
    name: 'Tech',
    color: '#6fa0e8',
    topics: [
      ['Public-key cryptography', 'How strangers exchange secrets over a public network.'],
      ['Internet protocol suite', 'The layered rules that make the internet work.'],
      ['Domain Name System', 'The internet\'s phone book.'],
      ['HTTPS', 'What the padlock in your browser actually protects.'],
      ['Machine learning', 'How computers learn patterns from data instead of rules.'],
      ['Neural network (machine learning)', 'The loosely brain-inspired math behind modern AI.'],
      ['Large language model', 'How chatbots like this one actually work under the hood.'],
      ['Moore\'s law', 'The decades-long doubling that drove the computing revolution.'],
      ['Password strength', 'Why length beats complexity for passwords.'],
      ['Multi-factor authentication', 'The single best step to protect your accounts.'],
      ['Phishing', 'How attackers trick people, and the red flags to spot.'],
      ['Social engineering (security)', 'Hacking humans instead of computers.'],
      ['Data compression', 'How a file can shrink without losing information.'],
      ['Open-source software', 'Why so much of the world runs on free, shared code.'],
      ['Cloud computing', 'What "the cloud" physically is.'],
      ['Algorithm', 'Step-by-step recipes that run the modern world.'],
      ['Turing machine', 'The simple imaginary machine that defines what\'s computable.'],
      ['Binary number', 'How everything digital boils down to 1s and 0s.'],
      ['Unicode', 'How every language (and emoji) fits into one text system.'],
      ['Operating system', 'The software that manages everything else.'],
      ['Big O notation', 'How programmers measure how code scales.'],
      ['Quantum computing', 'What it can and can\'t do better than regular computers.'],
      ['Blockchain', 'The shared ledger idea behind cryptocurrency, minus the hype.']
    ]
  }
];

if (typeof module !== 'undefined') module.exports = TOPIC_POOL;
